[package]
name = "demo"
version = "0.1.2"
authors = ["Antipy V.O.F. <devs@antipy.com>"]
edition = "2018"
description = "demo"

[lib]
name = "martens_martens_icons_lib"
crate_type = ["dylib", "lib"]

[dependencies]
image = "0.23.9"

[profile.release]
debug = true
lto = true

