[package]
name = "demo"
version = "0.1.2"
authors = ["Antipy V.O.F. <devs@antipy.com>"]
edition = "2018"
description = "demo"

[lib]
name = "martens_martens_icons_lib"
crate_type = ["dylib", "lib"]

[profile.release]
lto = true

