name: ci

on:
  push:
    branches: [master]
    tags: ["**"]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build-${{ matrix.os }}-rust-${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: ["1.47.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Bundle (macos)
        run: cargo build --bin=gui --release
