name: ci

on:
  push:
    branches: [master]
    tags: ["**"]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build-${{ matrix.os }}-rust-${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: ["1.46.0"]
    steps:
      - name: Bundle (macos)
        run: cargo bundle --bin=gui --release
